### PR TITLE
move #2 to it's on branch so other people can work on it

### PR DESCRIPTION
**Pull request by voldemortensen**
Still a bit to do. i.e. get it compatible with parent class.

### CODE REVIEW

**Comment by georgestephanis** [comment]
:+1: for working off the main repo.

**Comment by valendesigns** [comment]
I'll clean this up so it passes the coding standards tests probably tomorrow.

**Comment by aaroncampbell** [comment]
I put in a pull request (#29) with working TOTP code. I tried to integrate some of this in there, but it needs to use base32 not base64 (to the best of my knowledge there isn't a way to use base64 in this context). Feel free to rob from that pr whatever might be useful

**Comment by georgestephanis** [comment]
Closing in lieu of #31, which is merged.

**Pull request closed without merging**
