### PR TITLE
TOTP: Pre-encode spaces to fix iOS issue with URLs containing spaces

### LINKED ISSUE #70: iOS chokes on spaces in site name when scanning QR Code
Apparently it's a known issue that iOS doesn't like spaces in URLs. Since we put the site name in the URL, it needs to be encoded beforehand to handle any potential spaces

### PR DESCRIPTION
**Pull request by aaroncampbell**
This fixes #70

### CODE REVIEW

**Comment by valendesigns** [comment]
@aaroncampbell Which devices have you tested this change on so far?

**Comment by aaroncampbell** [comment]
@valendesigns  I have no iDevices, but got people to test. I think the only things it's been tested with is the iPhone 5 and 6.

**Comment by valendesigns** [comment]
Do you have an Android device to test with?

**Comment by valendesigns** [comment]
Tests are now passing and this PR is ready for merge, that is once it's been verified that no regression exists with non iOS devices. I highly doubt there is a regression here, but it's better to check than to assume. Cheers!

**Comment by aaroncampbell** [comment]
Oh yeah! I have several android devices. I tested it on my my phone (Galaxy S5), and three tablets (varying Galaxy tabs).

**Comment by valendesigns** [comment]
Perfect! Thanks Aaron.

**Pull request merged**
