### PR TITLE
Add email provider tests, some core tests, and small bug fixes

### PR DESCRIPTION
**Pull request by scotchfield**
I started by adding test coverage for the email provider and a few basic tests for the core class. In addition, I added a few safety checks in email. Also using the mockmailer so email output can be tested (used in one test at the moment). Please let me know what you think.
Thanks!

### CODE REVIEW

**Comment by scotchfield** [comment]
I don't see these errors locally, is there something in the Travis script that's causing this?

**Comment by valendesigns** [comment]
I'll test it out on my setup later tonight.

**Comment by scotchfield** [comment]
It looks like an older version of phpunit that predates assertNotFalse. I can rewrite, or is it possible to move to a newer version on travis?

**Comment by valendesigns** [comment]
It's what is on Travis. I would just rewrite the test. It's simple enough.

**Comment by scotchfield** [comment]
Will do. Thanks!

**Comment by valendesigns** [comment]
Looks like you need to define `SERVER_NAME`, as well.

**Comment by scotchfield** [comment]
This is a strange one. In WP_UnitTestCase, there's a hook to wp_mail to set the server name in setUp (example.com) if it's not set already and to tear it down afterwards (set_wp_mail_globals). I can override, but it kind of stinks not knowing why that's not being called in the first place. Just going to test a few things locally. Sorry about the fails!

**Comment by valendesigns** [comment]
I don't believe we need to `setUp` and `tearDown` before each test just to change server globals. Couldn't we use `setUpBeforeClass` & `tearDownAfterClass` instead?

**Comment by scotchfield** [comment]
That's a really good observation, thanks! I'll push a change now.

**Comment by georgestephanis** [comment]
@valendesigns Is this good to merge?

**Comment by georgestephanis** [comment]
Reviewed, looks good to me and all checks pass.  Merging.

**Pull request merged**
